-- MySQL Script generated by MySQL Workbench
-- Sun Jun  2 19:55:26 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema rede_social
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema rede_social
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `rede_social` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `rede_social` ;

-- -----------------------------------------------------
-- Table `rede_social`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rede_social`.`usuario` (
  `ID` INT NOT NULL,
  `Nome` VARCHAR(45) NULL DEFAULT NULL,
  `Data_nascimento` DATE NULL DEFAULT NULL,
  `Endereco_de_email` VARCHAR(45) NULL DEFAULT NULL,
  `senha` VARCHAR(45) NULL DEFAULT NULL,
  `Foto_de_perfil` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `senha` (`senha` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `rede_social`.`chat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rede_social`.`chat` (
  `ID_chat` INT NOT NULL,
  `ID_remetente` INT NULL DEFAULT NULL,
  `ID_destinatario` INT NULL DEFAULT NULL,
  `Texto_mensagem` VARCHAR(45) NULL DEFAULT NULL,
  `data_e_hora_mensagem` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`ID_chat`),
  INDEX `ID_remetente` (`ID_remetente` ASC) VISIBLE,
  INDEX `ID_destinatario` (`ID_destinatario` ASC) VISIBLE,
  CONSTRAINT `chat_ibfk_1`
    FOREIGN KEY (`ID_remetente`)
    REFERENCES `rede_social`.`usuario` (`ID`),
  CONSTRAINT `chat_ibfk_2`
    FOREIGN KEY (`ID_destinatario`)
    REFERENCES `rede_social`.`usuario` (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `rede_social`.`postagem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rede_social`.`postagem` (
  `ID_postagem` INT NOT NULL,
  `ID_usuario` INT NULL DEFAULT NULL,
  `Texto_da_postagem` VARCHAR(45) NULL DEFAULT NULL,
  `data_e_hora` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`ID_postagem`),
  INDEX `ID_usuario` (`ID_usuario` ASC) VISIBLE,
  CONSTRAINT `postagem_ibfk_1`
    FOREIGN KEY (`ID_usuario`)
    REFERENCES `rede_social`.`usuario` (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `rede_social`.`comentario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rede_social`.`comentario` (
  `ID_comentario` INT NOT NULL,
  `ID_postagem` INT NULL DEFAULT NULL,
  `ID_usuario` INT NULL DEFAULT NULL,
  `Texto_comentario` VARCHAR(45) NULL DEFAULT NULL,
  `data_e_hora_comentario` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`ID_comentario`),
  INDEX `ID_postagem` (`ID_postagem` ASC) VISIBLE,
  INDEX `ID_usuario` (`ID_usuario` ASC) VISIBLE,
  CONSTRAINT `comentario_ibfk_1`
    FOREIGN KEY (`ID_postagem`)
    REFERENCES `rede_social`.`postagem` (`ID_postagem`),
  CONSTRAINT `comentario_ibfk_2`
    FOREIGN KEY (`ID_usuario`)
    REFERENCES `rede_social`.`usuario` (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `rede_social`.`conexao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rede_social`.`conexao` (
  `ID_conexao` INT NOT NULL,
  `ID_usuario` INT NULL DEFAULT NULL,
  `ID_amigo` INT NULL DEFAULT NULL,
  `data_conexao` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`ID_conexao`),
  INDEX `ID_usuario` (`ID_usuario` ASC) VISIBLE,
  INDEX `ID_amigo` (`ID_amigo` ASC) VISIBLE,
  CONSTRAINT `conexao_ibfk_1`
    FOREIGN KEY (`ID_usuario`)
    REFERENCES `rede_social`.`usuario` (`ID`),
  CONSTRAINT `conexao_ibfk_2`
    FOREIGN KEY (`ID_amigo`)
    REFERENCES `rede_social`.`usuario` (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `rede_social`.`curtida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rede_social`.`curtida` (
  `ID_curtida` INT NOT NULL,
  `ID_postagem` INT NULL DEFAULT NULL,
  `ID_usuario` INT NULL DEFAULT NULL,
  `data_e_hora_curtida` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`ID_curtida`),
  INDEX `ID_postagem` (`ID_postagem` ASC) VISIBLE,
  INDEX `ID_usuario` (`ID_usuario` ASC) VISIBLE,
  CONSTRAINT `curtida_ibfk_1`
    FOREIGN KEY (`ID_postagem`)
    REFERENCES `rede_social`.`postagem` (`ID_postagem`),
  CONSTRAINT `curtida_ibfk_2`
    FOREIGN KEY (`ID_usuario`)
    REFERENCES `rede_social`.`usuario` (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
